export MONGO_INITDB_ROOT_USERNAME=test
export MONGO_INITDB_ROOT_PASSWORD=abc123
export MONGO_INITDB_DATABASE=blockers

docker run --name mongodb \
    -p 27017:27017 \
    -e MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME \
    -e MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD \
    -e MONGO_INITDB_DATABASE=$MONGO_INITDB_DATABASE \
    -d mongo:latest

export MONGODB_URI=mongodb://$MONGO_INITDB_ROOT_USERNAME:$MONGO_INITDB_ROOT_PASSWORD@localhost:27017/
export MONGODB_DATBASE=$MONGO_INITDB_DATABASE

npm run dev