# Default values for wordcloud-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

wordcloudImage:
  repository: calshi/wordcloud-app
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

presentationImage:
  repository: calshi/cncf-pres
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

mongoImage:
  repository: mongo
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"
  username: test
  password: abc123
  database: admin

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  wordcloudPort: 8080
  presPort: 8081
