apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wordcloud-chart.fullname" . }}
  labels:
    {{- include "wordcloud-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "wordcloud-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "wordcloud-chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: wordcloud
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.wordcloudImage.repository }}:{{ .Values.wordcloudImage.tag }}"
          imagePullPolicy: {{ .Values.wordcloudImage.pullPolicy }}
          env:
          - name: MONGODB_DATABASE
            value: "{{ .Values.mongoImage.database }}"
          - name: MONGODB_URI
            value: mongodb://{{ .Values.mongoImage.username }}:{{ .Values.mongoImage.password }}@localhost:27017/
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: mongodb
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.mongoImage.repository }}:{{ .Values.mongoImage.tag }}"
          imagePullPolicy: {{ .Values.mongoImage.pullPolicy }}
          env:          
          - name: "MONGO_INITDB_ROOT_USERNAME"
            value: "{{ .Values.mongoImage.username }}"
          - name: "MONGO_INITDB_ROOT_PASSWORD"
            value: "{{ .Values.mongoImage.password }}"
          - name: "MONGO_INITDB_DATABASE"
            value: "{{ .Values.mongoImage.database }}"                        
          ports:
            - name: db
              containerPort: 27017
              protocol: TCP                  
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
