apiVersion: v1
kind: Service
metadata:
  name: presentation-service
  labels:
    {{- include "wordcloud-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.presPort }}
      targetPort: pres
      protocol: TCP
      name: http
  selector:
    {{- include "wordcloud-chart.selectorLabels" . | nindent 4 }}
